### ISSUE TITLE
Change repository name to `tinkerbell/ipxe`

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/boots-ipxe#18]
The current user experience for importing `tinkerbell/boots-ipxe` is that the import must be renamed.

```Go
import (
    ipxe "github.com/tinkerbell/boots-ipxe"
)
```
The guidance from the Go maintainers is that _"good package names should not require renaming."_ -- [ref](https://github.com/golang/go/wiki/CodeReviewComments#imports)

For this reason, I propose we rename this repository to `tinkerbell/ipxe`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by displague** [comment]
`tinkerbell/ipxe` is what was initially proposed and IIRC, I requested a `boots-` prefix to show that this is a `boots` specific and descended `ipxe` project.  Reorganization within `tinkerbell/boots` was also suggested.

Given where we are and how recent this change was, this rename seems reasonable to me. Some alternatives might be:

* github.com/tinkerbell/ipxe-boots (which would import as `ipxe`)
* github.com/tinkerbell/boots-ipxe/servers/{ipxe,http,tftp}
* github.com/tinkerbell/boots-ipxe/ipxe (everything else has it's own directory)

**Comment by jacobweinstock** [comment]
Hy @displague, thanks for weighing in on this. Would you mind expanding on _"to show that this is a boots specific and descended ipxe project."_?

I'm not sure I'm convinced of the need to have such a coupling with Boots proper. Naming a library based on a client also seems unorthodox.

This repo stands on its own in terms of functionality and value. Its first library client is itself. It has a CLI that imports the library. Boots will just be another client.

**Comment by jacobweinstock** [comment]
the name `ipxedust` was suggested in today's community meeting by @detiber. I quite like it. There weren't any objections. I will plan to go forward with this name change to `ipxedust`.
